# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-23 11:51
from __future__ import unicode_literals

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('prefapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mnumber',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
