# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-24 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefapp', '0004_auto_20200524_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='msg',
            field=models.TextField(null=True),
        ),
    ]
